name: spring-init-test
services:
  - name: web
    type: web
    build:
      dockerfile: Dockerfile
    port: 8080
    env:
      - key: PORT
        value: "8080"
    health_check:
      path: /
      port: 8080
      grace_period: 30s
    routes:
      - path: /